FROM openjdk:16

MAINTAINER mail@ingvord.ru

ARG JAR_FILE
ADD ${JAR_FILE} /app/bin/run.jar

WORKDIR /app

ENV JAVA_TOOL_OPTIONS=""
ENV TANGO_HOST=localhost:10000
ENV MAGIX_HOST=localhost:8080
ENV OAPORT=30100
ENV CTRL1=1.1.1.1:1234
ENV CTRL2=1.1.1.2:1234

CMD java -server -DOAPort=$OAPORT -DTANGO_HOST=$TANGO_HOST -DMAGIX_HOST=$MAGIX_HOST -DCTRL1=$CTRL1 -DCTRL2=$CTRL2 -jar /app/bin/run.jar virtual